apiVersion: v1
kind: ServiceAccount
metadata:
  name: technical-service-account
  namespace: smart-devices

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: smart-devices
  name: technical-role
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: technical-role-binding
  namespace: smart-devices
subjects:
  - kind: ServiceAccount
    name: technical-service-account
    namespace: smart-devices
roleRef:
  kind: Role
  name: technical-role
  apiGroup: rbac.authorization.k8s.io
