apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: smart-devices
  name: owner-role
rules:
  - apiGroups: [""]
    resources: ["services", "configmaps", "statefulsets"]
    verbs: ["get", "list", "watch"]